
var strings = exports.strings = {
    'en': {
        close: 'Close',
        stop: 'Stop',
        open: 'Open',
        controller: 'CurtainOperation',
        position: 'CurtainPosition',
        more_setting: 'MoreSetting',
        percent: ' Position:',
        setting: 'setting',
        Curtaincalibration: 'Calibration',
        Curtain_reversal: 'CurtainPositive',
        featureSetting: 'Shortcut settings',
        commonSetting: 'Common settings',
        deviceName: 'Device name',
        locationManagement: 'Locations',
        shareDevice: 'Share device',
        ifttt: 'Automation',
        firmwareUpgrate: 'Check for firmware updates',
        moreSetting: 'Additional settings',
        addToDesktop: 'Add to Home screen',
        resetDevice: 'Reset device',
        licenseAndPolicy: 'User Agreement & Privacy Policy',
        device_more_activity_rename: 'Rename',
        device_more_activity_about: 'About',
        device_more_activity_help: 'Tutorial',
        device_more_activity_firmware_update: 'Check for firmware updates',
        device_more_activity_noti_quick_op: 'Notification center shortcuts',
        device_more_activity_unbind: 'Remove device',
        device_more_activity_feedback: 'Feedback',
        device_more_activity_scence: 'Automation',
        device_more_activity_help_feedback: 'Help',
        device_more_activity_reset: 'Reset',
        device_more_activity_setting: 'Settings',
        device_more_activity_common_setting: 'General settings',
        device_more_activity_network_info: 'Network info',
        device_more_activity_license_privacy: 'User Agreement and Privacy Policy',
        device_more_activity_license: 'User Agreement',
        device_more_activity_privacy: ' Privacy Policy ',
        device_more_activity_cancel_license_privacy: 'Withdraw the authorization from User Agreement and Privacy Policy',
        OpenLibList: 'open source library test',
        ViewTest: ' test view',
        cancel: "Cancel",
        ok: "OK",
        save: "Save",
        saved: "Saved successfully",
        voiceBroadcast: 'voice control',
        start_calibration: 'start calibration',
        stop_calibration: 'stop calibration',
        calibrationing: 'calibrationing',
        calibration_failure: 'calibration failure',
        calibration_successful: 'calibration successful',
        device_time_zone: 'device time zone',
        version: 'version'
    },
    'zh': {
        close: '关闭窗帘',
        stop: '暂停窗帘',
        open: '打开窗帘',
        controller: '窗帘控制',
        position: '窗帘位置',
        more_setting: '更多设置',
        percent: '窗帘位置:',
        setting: '设置',
        Curtaincalibration: '窗帘校准',
        Curtain_reversal: '窗帘正反转',
        featureSetting: '功能设置',
        commonSetting: '通用设置',
        deviceName: '设备名称',
        locationManagement: '位置管理',
        shareDevice: '设备共享',
        ifttt: '自动化',
        firmwareUpgrate: '检查固件升级',
        moreSetting: '更多设置',
        addToDesktop: '添加到桌面',
        resetDevice: '重置设备',
        licenseAndPolicy: '使用条款和隐私政策',
        device_more_activity_rename: '重命名',
        device_more_activity_about: '关于',
        device_more_activity_help: '玩法教程',
        device_more_activity_firmware_update: '检查固件更新',
        device_more_activity_noti_quick_op: '通知中心快捷开关',
        device_more_activity_unbind: '删除设备',
        device_more_activity_feedback: '反馈',
        device_more_activity_reset: '重置',
        device_more_activity_setting: '设置',
        device_more_activity_scence: '智能',
        device_more_activity_help_feedback: '使用帮助',
        device_more_activity_common_setting: '通用设置',
        device_more_activity_network_info: '网络信息',
        device_more_activity_license_privacy: '使用条款和隐私政策',
        device_more_activity_license: '使用条款',
        device_more_activity_privacy: '隐私政策',
        device_more_activity_cancel_license_privacy: '撤销“使用条款和隐私政策”授权',
        home_title: '虚拟设备',
        home_subtitle: '子设备',
        control_demo: ' 控制示例',
        cloud_debug: ' 云端调试',
        my_product: ' 创建自己的产品',
        OpenLibList: ' 第三方库测试',
        ViewTest: ' 常用的 view 测试',
        start_calibration: '开始校准',
        stop_calibration: '停止校准',
        calibrationing: '校准中',
        calibration_failure: '校准失败',
        calibration_successful: '校准成功',
        device_time_zone: '设备时区',
        version: '版本'
    }
};
